### ISSUE TITLE
row dimensionality issue

### ISSUE THREAD

**Issue by NienkeMekkes** [kieranrcampbell/clonealign#10]
Thank you for uploading this useful tool. I have a question about the code. When I try to run the clonealign function, I get the error message "copy_number_data must have same number of genes (rows) as gene_expression_data". The rownames of my cnv matrix and my expression matrix are of the same size and contain the same genes. When looking in the code, could it be that `if(nrow(L) != G)` should be changed to `if(nrow(L) != N)`, or do you think this is caused by something else?

`  N <- nrow(Y)`
  `G <- ncol(Y)`
`L <- copy_number_data`

`  if(nrow(L) != G) {
    stop("copy_number_data must have same number of genes (rows) as gene_expression_data")
  }

Thank you for your time

  `

**Comment by kieranrcampbell** [comment]
Hi @NienkeMekkes 

I think this might be because of a stupid choice I made in the initial design:
- `Y` should be cells (rows) by genes (columns)
- `L` should be genes (rows) by clones (columns)

so you want `ncol(Y) == nrow(L)`

which I think might mean transposing your Y before input-  does that fix it?

I would change this in the code but feel I have to leave it for backwards compatibility

**Comment by NienkeMekkes** [comment]
clonealign started running after the quick transpose, thanks for the quick reply!
